version: "3.4"
services:
  website:
    entrypoint: ["echo", "Website is disabled in dev mode"]
    ports:
      - 3001:3000
  api:
    volumes:
      - ./api:/usr/src/app
    environment:
      - "NODE_ENV=development"
    command: >
      sh -c "npm install && supervisor -w . -- --inspect=0.0.0.0:9229 server.js"
  fetch_data:
    volumes:
      - ./fetchData:/usr/src/app
    environment:
      - "NODE_ENV=development"
    command: >
      sh -c "npm install && supervisor -w . -n exit -- --inspect=0.0.0.0:9229 server.js"
